# Generated by Django 3.0.7 on 2020-06-22 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, default=None, help_text='The value of the label', null=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='The user that created this label', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('disease', models.ManyToManyField(related_name='labels', to='disease.Disease')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(help_text='The image that has been uploaded', upload_to='')),
                ('created_by', models.ForeignKey(editable=False, help_text='The user that uploaded this image', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(help_text='The labels associated with this image', related_name='images_using_label', to='imaging.ImageLabel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
