# Generated by Django 3.0.7 on 2020-06-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalimage',
            old_name='labels',
            new_name='label',
        ),
    ]
