# Generated by Django 3.0.7 on 2020-06-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationcode',
            name='identifier',
            field=models.TextField(blank=True, default=None, help_text="Classification standard's code for this condition", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='classificationstandard',
            name='name',
            field=models.TextField(help_text='The name of this standard (ICD-10, ICD-9 etc)', unique=True),
        ),
    ]
