# Generated by Django 3.0.7 on 2020-06-22 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(blank=True, default=None, help_text='The url that was requested', null=True)),
                ('request_dump', models.TextField(blank=True, default=None, help_text='A string dump of the request headers', null=True)),
                ('user', models.ForeignKey(blank=True, default=None, editable=False, help_text='The user that this event relates to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
