# Generated by Django 3.0.7 on 2020-06-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='request_dump',
            field=models.TextField(blank=True, default=None, help_text='A string dump of the request headers', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.TextField(blank=True, default=None, help_text='The url that was requested', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, default=None, editable=False, help_text='The user that this event relates to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
